spring.application.name=HearingsDemo
server.port=8081

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}?sslmode=require&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRITICAL: This stops Hibernate from asking the Pooler for "Metadata" on startup.
# The Supabase Transaction Pooler (6543) often fails when asked for metadata.
spring.jpa.properties.hibernate.temp.use_jbdc_metadata_defaults=false
spring.jpa.properties.hibernate.boot.allow_jbdc_metadata_access=false