spring.application.name=HearingsDemo
server.port=8081

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/hearings_demo}
spring.datasource.username=${DB_PASSWORD:local_user}
spring.datasource.password=${DB_PASSWORD:local_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRITICAL: This stops Hibernate from asking the Pooler for "Metadata" on startup.
# The Supabase Transaction Pooler (6543) often fails when asked for metadata.
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# # 3. CONNECTION POOL TUNING
# # Cloud poolers prefer small, active pools.
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1